#!/bin/bash

TOGET="http://c.xkcd.com/random/comic/"
if [ ${#} -eq 1 ]
  then
    if [ ${1} = "current" ]
      then
        TOGET="http://www.xkcd.com/"
      else
        if [[ ${1} =~ ^[0-9]+$ ]]
          then
            TOGET="http://www.xkcd.com/${1}/"
        fi
    fi
fi

# get HTML file
FILENAME=".xkcdFile"
wget -q -O ${FILENAME} ${TOGET}

# get data from HTML file
TITLE=$(cat ${FILENAME} | grep -Pzo '(?<= alt=")(.+?)(?=" />)')
CAPTION=$(cat ${FILENAME} | grep -Pzo '(?<=" title=")(.+?)(?=" alt=".+?" />)' | recode html..ascii)
URL=$(cat ${FILENAME} | grep -Pzo '(?<=<div id="comic">\n<img src=")(.+?)(?=")')
RELURL=$(echo ${URL} | grep -Po '(?<=//imgs\.xkcd\.com/comics/).+$')

# get image file
wget -q "http:${URL}"

# print out message
printf "\nTitle: ${TITLE}\nCaption: ${CAPTION}\nURL: ${RELURL}\n\n"

# display image file
# uses code from http://stackoverflow.com/questions/25585625
wmctrl -T master$$ -r :ACTIVE: ; display ${RELURL} & sleep 0.1 ; wmctrl -a master$$
IMGPCS=$!

# wait for user input to complete the rest
read -s -n 1

# remove files
rm ${FILENAME}
rm ${RELURL}
kill ${IMGPCS}
